// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package delete_salary_change_test is a generated GoMock package.
package delete_salary_change_test

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgtype "github.com/jackc/pgx/v5/pgtype"
)

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// DeleteChange mocks base method.
func (m *Mockrepo) DeleteChange(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChange", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChange indicates an expected call of DeleteChange.
func (mr *MockrepoMockRecorder) DeleteChange(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChange", reflect.TypeOf((*Mockrepo)(nil).DeleteChange), ctx, id)
}
