// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package estimate_test is a generated GoMock package.
package estimate_test

import (
	context "context"
	reflect "reflect"
	time "time"

	get_salary_report "salary_calculator/internal/dto/get_salary_report"
	dbstore "salary_calculator/internal/generated/dbstore"
	vacation_pay "salary_calculator/internal/services/vacation_pay"

	gomock "github.com/golang/mock/gomock"
)

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// GetLatestChangeBeforeDate mocks base method.
func (m *Mockrepo) GetLatestChangeBeforeDate(ctx context.Context, changeFrom string) (dbstore.SalaryChange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestChangeBeforeDate", ctx, changeFrom)
	ret0, _ := ret[0].(dbstore.SalaryChange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestChangeBeforeDate indicates an expected call of GetLatestChangeBeforeDate.
func (mr *MockrepoMockRecorder) GetLatestChangeBeforeDate(ctx, changeFrom interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestChangeBeforeDate", reflect.TypeOf((*Mockrepo)(nil).GetLatestChangeBeforeDate), ctx, changeFrom)
}

// MockvacationPayService is a mock of vacationPayService interface.
type MockvacationPayService struct {
	ctrl     *gomock.Controller
	recorder *MockvacationPayServiceMockRecorder
}

// MockvacationPayServiceMockRecorder is the mock recorder for MockvacationPayService.
type MockvacationPayServiceMockRecorder struct {
	mock *MockvacationPayService
}

// NewMockvacationPayService creates a new mock instance.
func NewMockvacationPayService(ctrl *gomock.Controller) *MockvacationPayService {
	mock := &MockvacationPayService{ctrl: ctrl}
	mock.recorder = &MockvacationPayServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvacationPayService) EXPECT() *MockvacationPayServiceMockRecorder {
	return m.recorder
}

// CalculatePay mocks base method.
func (m *MockvacationPayService) CalculatePay(ctx context.Context, from, to time.Time) (*vacation_pay.Pay, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculatePay", ctx, from, to)
	ret0, _ := ret[0].(*vacation_pay.Pay)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculatePay indicates an expected call of CalculatePay.
func (mr *MockvacationPayServiceMockRecorder) CalculatePay(ctx, from, to interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculatePay", reflect.TypeOf((*MockvacationPayService)(nil).CalculatePay), ctx, from, to)
}

// MockreportUsecase is a mock of reportUsecase interface.
type MockreportUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockreportUsecaseMockRecorder
}

// MockreportUsecaseMockRecorder is the mock recorder for MockreportUsecase.
type MockreportUsecaseMockRecorder struct {
	mock *MockreportUsecase
}

// NewMockreportUsecase creates a new mock instance.
func NewMockreportUsecase(ctrl *gomock.Controller) *MockreportUsecase {
	mock := &MockreportUsecase{ctrl: ctrl}
	mock.recorder = &MockreportUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreportUsecase) EXPECT() *MockreportUsecaseMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockreportUsecase) Do(ctx context.Context, in get_salary_report.In) (*get_salary_report.Out, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, in)
	ret0, _ := ret[0].(*get_salary_report.Out)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockreportUsecaseMockRecorder) Do(ctx, in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockreportUsecase)(nil).Do), ctx, in)
}
