// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package add_test is a generated GoMock package.
package add_test

import (
	context "context"
	reflect "reflect"

	dbstore "salary_calculator/internal/generated/dbstore"

	gomock "github.com/golang/mock/gomock"
)

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// InsertVacation mocks base method.
func (m *Mockrepo) InsertVacation(ctx context.Context, arg dbstore.InsertVacationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertVacation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertVacation indicates an expected call of InsertVacation.
func (mr *MockrepoMockRecorder) InsertVacation(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertVacation", reflect.TypeOf((*Mockrepo)(nil).InsertVacation), ctx, arg)
}
