// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package vacation_pay_test is a generated GoMock package.
package vacation_pay_test

import (
	context "context"
	reflect "reflect"

	dbstore "salary_calculator/internal/generated/dbstore"
	work_calendar_parser "salary_calculator/internal/pkg/http/work_calendar_parser"

	gomock "github.com/golang/mock/gomock"
)

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// ListBonuses mocks base method.
func (m *Mockrepo) ListBonuses(ctx context.Context) ([]dbstore.Bonuse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBonuses", ctx)
	ret0, _ := ret[0].([]dbstore.Bonuse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBonuses indicates an expected call of ListBonuses.
func (mr *MockrepoMockRecorder) ListBonuses(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBonuses", reflect.TypeOf((*Mockrepo)(nil).ListBonuses), ctx)
}

// ListChanges mocks base method.
func (m *Mockrepo) ListChanges(ctx context.Context) ([]dbstore.SalaryChange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChanges", ctx)
	ret0, _ := ret[0].([]dbstore.SalaryChange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChanges indicates an expected call of ListChanges.
func (mr *MockrepoMockRecorder) ListChanges(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChanges", reflect.TypeOf((*Mockrepo)(nil).ListChanges), ctx)
}

// MockcalendarParser is a mock of calendarParser interface.
type MockcalendarParser struct {
	ctrl     *gomock.Controller
	recorder *MockcalendarParserMockRecorder
}

// MockcalendarParserMockRecorder is the mock recorder for MockcalendarParser.
type MockcalendarParserMockRecorder struct {
	mock *MockcalendarParser
}

// NewMockcalendarParser creates a new mock instance.
func NewMockcalendarParser(ctrl *gomock.Controller) *MockcalendarParser {
	mock := &MockcalendarParser{ctrl: ctrl}
	mock.recorder = &MockcalendarParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcalendarParser) EXPECT() *MockcalendarParserMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockcalendarParser) Parse(year, month int) (*work_calendar_parser.WorkdayResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", year, month)
	ret0, _ := ret[0].(*work_calendar_parser.WorkdayResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockcalendarParserMockRecorder) Parse(year, month interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockcalendarParser)(nil).Parse), year, month)
}
