// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package list_test is a generated GoMock package.
package list_test

import (
	context "context"
	reflect "reflect"

	dbstore "salary_calculator/internal/generated/dbstore"

	gomock "github.com/golang/mock/gomock"
)

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// ListVacations mocks base method.
func (m *Mockrepo) ListVacations(ctx context.Context) ([]dbstore.Vacation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVacations", ctx)
	ret0, _ := ret[0].([]dbstore.Vacation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVacations indicates an expected call of ListVacations.
func (mr *MockrepoMockRecorder) ListVacations(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVacations", reflect.TypeOf((*Mockrepo)(nil).ListVacations), ctx)
}
