// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package get_salary_report_test is a generated GoMock package.
package get_salary_report_test

import (
	context "context"
	reflect "reflect"
	value_objects "salary_calculator/internal/dto/value_objects"
	dbstore "salary_calculator/internal/generated/dbstore"
	work_calendar "salary_calculator/internal/pkg/http/work_calendar"
	calculator "salary_calculator/internal/services/calculator"
	work_days "salary_calculator/internal/services/work_days"

	gomock "github.com/golang/mock/gomock"
)

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// GetBonusByDate mocks base method.
func (m *Mockrepo) GetBonusByDate(ctx context.Context, date string) (dbstore.Bonuse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBonusByDate", ctx, date)
	ret0, _ := ret[0].(dbstore.Bonuse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBonusByDate indicates an expected call of GetBonusByDate.
func (mr *MockrepoMockRecorder) GetBonusByDate(ctx, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBonusByDate", reflect.TypeOf((*Mockrepo)(nil).GetBonusByDate), ctx, date)
}

// ListChanges mocks base method.
func (m *Mockrepo) ListChanges(ctx context.Context) ([]dbstore.SalaryChange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChanges", ctx)
	ret0, _ := ret[0].([]dbstore.SalaryChange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChanges indicates an expected call of ListChanges.
func (mr *MockrepoMockRecorder) ListChanges(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChanges", reflect.TypeOf((*Mockrepo)(nil).ListChanges), ctx)
}

// MocksalaryCalculator is a mock of salaryCalculator interface.
type MocksalaryCalculator struct {
	ctrl     *gomock.Controller
	recorder *MocksalaryCalculatorMockRecorder
}

// MocksalaryCalculatorMockRecorder is the mock recorder for MocksalaryCalculator.
type MocksalaryCalculatorMockRecorder struct {
	mock *MocksalaryCalculator
}

// NewMocksalaryCalculator creates a new mock instance.
func NewMocksalaryCalculator(ctrl *gomock.Controller) *MocksalaryCalculator {
	mock := &MocksalaryCalculator{ctrl: ctrl}
	mock.recorder = &MocksalaryCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksalaryCalculator) EXPECT() *MocksalaryCalculatorMockRecorder {
	return m.recorder
}

// CalculateSalary mocks base method.
func (m *MocksalaryCalculator) CalculateSalary(sCtx value_objects.SalaryCalculationContext, extraPayments value_objects.ExtraPaymentsCollection) calculator.SalaryCalculationResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateSalary", sCtx, extraPayments)
	ret0, _ := ret[0].(calculator.SalaryCalculationResult)
	return ret0
}

// CalculateSalary indicates an expected call of CalculateSalary.
func (mr *MocksalaryCalculatorMockRecorder) CalculateSalary(sCtx, extraPayments interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateSalary", reflect.TypeOf((*MocksalaryCalculator)(nil).CalculateSalary), sCtx, extraPayments)
}

// MockworkdaysClient is a mock of workdaysClient interface.
type MockworkdaysClient struct {
	ctrl     *gomock.Controller
	recorder *MockworkdaysClientMockRecorder
}

// MockworkdaysClientMockRecorder is the mock recorder for MockworkdaysClient.
type MockworkdaysClientMockRecorder struct {
	mock *MockworkdaysClient
}

// NewMockworkdaysClient creates a new mock instance.
func NewMockworkdaysClient(ctrl *gomock.Controller) *MockworkdaysClient {
	mock := &MockworkdaysClient{ctrl: ctrl}
	mock.recorder = &MockworkdaysClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockworkdaysClient) EXPECT() *MockworkdaysClientMockRecorder {
	return m.recorder
}

// GetWorkdaysForMonth mocks base method.
func (m *MockworkdaysClient) GetWorkdaysForMonth(ctx context.Context, month, year int) (*work_calendar.WorkdayResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkdaysForMonth", ctx, month, year)
	ret0, _ := ret[0].(*work_calendar.WorkdayResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkdaysForMonth indicates an expected call of GetWorkdaysForMonth.
func (mr *MockworkdaysClientMockRecorder) GetWorkdaysForMonth(ctx, month, year interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkdaysForMonth", reflect.TypeOf((*MockworkdaysClient)(nil).GetWorkdaysForMonth), ctx, month, year)
}

// MockworkdaysCalculator is a mock of workdaysCalculator interface.
type MockworkdaysCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockworkdaysCalculatorMockRecorder
}

// MockworkdaysCalculatorMockRecorder is the mock recorder for MockworkdaysCalculator.
type MockworkdaysCalculatorMockRecorder struct {
	mock *MockworkdaysCalculator
}

// NewMockworkdaysCalculator creates a new mock instance.
func NewMockworkdaysCalculator(ctrl *gomock.Controller) *MockworkdaysCalculator {
	mock := &MockworkdaysCalculator{ctrl: ctrl}
	mock.recorder = &MockworkdaysCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockworkdaysCalculator) EXPECT() *MockworkdaysCalculatorMockRecorder {
	return m.recorder
}

// CalculateWorkDaysForMonth mocks base method.
func (m *MockworkdaysCalculator) CalculateWorkDaysForMonth(month work_calendar.WorkdayResponse) work_days.WorkdaysForMonth {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateWorkDaysForMonth", month)
	ret0, _ := ret[0].(work_days.WorkdaysForMonth)
	return ret0
}

// CalculateWorkDaysForMonth indicates an expected call of CalculateWorkDaysForMonth.
func (mr *MockworkdaysCalculatorMockRecorder) CalculateWorkDaysForMonth(month interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateWorkDaysForMonth", reflect.TypeOf((*MockworkdaysCalculator)(nil).CalculateWorkDaysForMonth), month)
}
