// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package delete_test is a generated GoMock package.
package delete_test

import (
	context "context"
	reflect "reflect"

	dbstore "salary_calculator/internal/generated/dbstore"

	gomock "github.com/golang/mock/gomock"
	pgtype "github.com/jackc/pgx/v5/pgtype"
)

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// DeleteDuty mocks base method.
func (m *Mockrepo) DeleteDuty(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDuty", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDuty indicates an expected call of DeleteDuty.
func (mr *MockrepoMockRecorder) DeleteDuty(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDuty", reflect.TypeOf((*Mockrepo)(nil).DeleteDuty), ctx, id)
}

// GetDutyByDate mocks base method.
func (m *Mockrepo) GetDutyByDate(ctx context.Context, date string) (dbstore.Duty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDutyByDate", ctx, date)
	ret0, _ := ret[0].(dbstore.Duty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDutyByDate indicates an expected call of GetDutyByDate.
func (mr *MockrepoMockRecorder) GetDutyByDate(ctx, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDutyByDate", reflect.TypeOf((*Mockrepo)(nil).GetDutyByDate), ctx, date)
}
