// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package delete_bonus_test is a generated GoMock package.
package delete_bonus_test

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgtype "github.com/jackc/pgx/v5/pgtype"
)

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// DeleteBonus mocks base method.
func (m *Mockrepo) DeleteBonus(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBonus", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBonus indicates an expected call of DeleteBonus.
func (mr *MockrepoMockRecorder) DeleteBonus(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBonus", reflect.TypeOf((*Mockrepo)(nil).DeleteBonus), ctx, id)
}
