// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package add_bonus_test is a generated GoMock package.
package add_test

import (
	"context"
	"reflect"

	"salary_calculator/internal/generated/dbstore"

	"github.com/golang/mock/gomock"
)

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// InsertBonus mocks base method.
func (m *Mockrepo) InsertBonus(ctx context.Context, arg dbstore.InsertBonusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBonus", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBonus indicates an expected call of InsertBonus.
func (mr *MockrepoMockRecorder) InsertBonus(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBonus", reflect.TypeOf((*Mockrepo)(nil).InsertBonus), ctx, arg)
}
