// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package calculator_test is a generated GoMock package.
package calculator_test

import (
	context "context"
	reflect "reflect"

	dbstore "salary_calculator/internal/generated/dbstore"

	gomock "github.com/golang/mock/gomock"
)

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// GetBonusByDate mocks base method.
func (m *Mockrepo) GetBonusByDate(ctx context.Context, date string) (dbstore.Bonuse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBonusByDate", ctx, date)
	ret0, _ := ret[0].(dbstore.Bonuse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBonusByDate indicates an expected call of GetBonusByDate.
func (mr *MockrepoMockRecorder) GetBonusByDate(ctx, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBonusByDate", reflect.TypeOf((*Mockrepo)(nil).GetBonusByDate), ctx, date)
}

// GetDutyByDate mocks base method.
func (m *Mockrepo) GetDutyByDate(ctx context.Context, date string) (dbstore.Duty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDutyByDate", ctx, date)
	ret0, _ := ret[0].(dbstore.Duty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDutyByDate indicates an expected call of GetDutyByDate.
func (mr *MockrepoMockRecorder) GetDutyByDate(ctx, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDutyByDate", reflect.TypeOf((*Mockrepo)(nil).GetDutyByDate), ctx, date)
}
