// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package get_salary_changes_test is a generated GoMock package.
package get_salary_changes_test

import (
	context "context"
	reflect "reflect"

	dbstore "salary_calculator/internal/generated/dbstore"

	gomock "github.com/golang/mock/gomock"
)

// Mockrepo is a mock of repo interface.
type Mockrepo struct {
	ctrl     *gomock.Controller
	recorder *MockrepoMockRecorder
}

// MockrepoMockRecorder is the mock recorder for Mockrepo.
type MockrepoMockRecorder struct {
	mock *Mockrepo
}

// NewMockrepo creates a new mock instance.
func NewMockrepo(ctrl *gomock.Controller) *Mockrepo {
	mock := &Mockrepo{ctrl: ctrl}
	mock.recorder = &MockrepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrepo) EXPECT() *MockrepoMockRecorder {
	return m.recorder
}

// ListChanges mocks base method.
func (m *Mockrepo) ListChanges(ctx context.Context) ([]dbstore.SalaryChange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChanges", ctx)
	ret0, _ := ret[0].([]dbstore.SalaryChange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChanges indicates an expected call of ListChanges.
func (mr *MockrepoMockRecorder) ListChanges(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChanges", reflect.TypeOf((*Mockrepo)(nil).ListChanges), ctx)
}
